import { Verdict } from '../../generated/prisma/client';
import { SCORING_CONFIG, ScoringConfigV1 } from './scoring.config';

const MS_PER_HOUR = 60 * 60 * 1000;

/**
 * Human-readable "why" copy for the factor breakdown. Templated here rather
 * than generated by the AI module (step 6): the score is deterministic, and
 * the labels have to stay stable so a stored v1 breakdown still reads as v1.
 */
export const SCORE_LABELS = {
  invalidPrice: 'A valid item price is needed to compute a regret score',
  missingBudget: 'A monthly budget is needed to compute a regret score',
  priceHigh: 'High price relative to your monthly budget',
  priceModerate: 'Moderate price relative to your monthly budget',
  priceLow: 'Low price relative to your monthly budget',
  similarOwnedYes: 'You already own something similar',
  similarOwnedNo: 'You do not already own something similar',
  saleYes: 'Sale or urgency language was detected on this item',
  saleNo: 'No sale or urgency language was detected',
  recencyHour: 'You discovered this within the last hour',
  recencyDay: 'You discovered this within the last day',
  recencyWeek: 'You discovered this within the last week',
  recencyOlder: 'This has been on your list for more than a week',
  categoryInsufficient: 'Not enough purchase history in this category to personalise this factor',
  categoryHigh: 'You have a high regret rate for purchases in this category',
  categoryModerate: 'You have some regret history in this category',
  categoryLow: 'You rarely regret purchases in this category',
} as const;

export interface ScoreFactor {
  label: string;
  weight: number;
}

/**
 * Shape written into `RegretScore.factorBreakdown`. The envelope (not a Prisma
 * column) is what lets v2 weights coexist with v1 rows.
 */
export interface StoredFactorBreakdown {
  version: number;
  factors: ScoreFactor[];
}

export interface CategoryRegretStatsInput {
  regretRate: number;
  sampleSize: number;
}

export interface ScoreComputationInput {
  price: number | null | undefined;
  discoveredAt: Date;
  detectedSaleLanguage: boolean;
  monthlyBudget: number | null | undefined;
  similarOwned: boolean;
  categoryRegretStats: CategoryRegretStatsInput | null;
}

export interface ScoreComputation {
  score: number;
  verdict: Verdict;
  factorBreakdown: StoredFactorBreakdown;
  pauseHours: number;
}

export function isUsableAmount(value: number | null | undefined): value is number {
  return typeof value === 'number' && Number.isFinite(value) && value > 0;
}

/**
 * `(price / monthlyBudget) * 100 * 0.3` with the v1 cap of 30. Written as
 * `(price / monthlyBudget) * max` so a v2 that changes `max` does not leave a
 * stray `0.3` behind.
 */
export function priceVsBudgetPoints(price: number, monthlyBudget: number): number {
  const { max } = SCORING_CONFIG.weights.priceVsBudget;
  return Math.min(max, (price / monthlyBudget) * max);
}

export function similarOwnedPoints(similarOwned: boolean): number {
  return similarOwned ? SCORING_CONFIG.weights.similarOwned.max : 0;
}

export function saleUrgencyPoints(detectedSaleLanguage: boolean): number {
  return detectedSaleLanguage ? SCORING_CONFIG.weights.saleUrgency.max : 0;
}

export function recencyPoints(
  discoveredAt: Date,
  now: Date,
  config: ScoringConfigV1 = SCORING_CONFIG,
): number {
  const ageHours = (now.getTime() - discoveredAt.getTime()) / MS_PER_HOUR;
  const bucket = config.recencyBuckets.find(
    (candidate) => candidate.maxAgeHours === null || ageHours <= candidate.maxAgeHours,
  );
  return (bucket ?? lastOf(config.recencyBuckets)).points;
}

export function categoryRegretRatePoints(
  stats: CategoryRegretStatsInput | null,
  config: ScoringConfigV1 = SCORING_CONFIG,
): number {
  const { max, defaultWhenInsufficientData, minSampleSize } = config.weights.categoryRegretRate;
  if (stats === null || stats.sampleSize < minSampleSize) {
    return defaultWhenInsufficientData;
  }
  return stats.regretRate * max;
}

export function verdictFor(score: number, config: ScoringConfigV1 = SCORING_CONFIG): Verdict {
  const threshold = config.verdictThresholds.find((candidate) => score <= candidate.max);
  return threshold?.verdict ?? lastOf(config.verdictThresholds).verdict;
}

/**
 * Pure lookup used by this module and, later, by Pauses (step 7). Not buried
 * inside `computeRegretScore` so a pause can be sized without computing a score.
 */
export function pauseHoursForPrice(
  price: number,
  config: ScoringConfigV1 = SCORING_CONFIG,
): number {
  const band = config.pauseHoursByPrice.find(
    (candidate) => candidate.maxPrice === null || price <= candidate.maxPrice,
  );
  return (band ?? lastOf(config.pauseHoursByPrice)).hours;
}

export function scoreCap(config: ScoringConfigV1 = SCORING_CONFIG): number {
  return lastOf(config.verdictThresholds).max;
}

export function computeRegretScore(
  input: ScoreComputationInput,
  now: Date = new Date(),
  config: ScoringConfigV1 = SCORING_CONFIG,
): ScoreComputation {
  const pauseHours = pauseHoursForPrice(isUsableAmount(input.price) ? input.price : 0, config);

  if (!isUsableAmount(input.price)) {
    return youDecide(SCORE_LABELS.invalidPrice, pauseHours, config);
  }

  if (!isUsableAmount(input.monthlyBudget)) {
    // Guard the division rather than producing Infinity / NaN: a zero or
    // missing budget means we cannot place the price on a 0–100 scale.
    return youDecide(SCORE_LABELS.missingBudget, pauseHours, config);
  }

  const priceVsBudget = priceVsBudgetPoints(input.price, input.monthlyBudget);
  const recency = recencyPoints(input.discoveredAt, now, config);

  const factors: ScoreFactor[] = [
    {
      label: priceVsBudgetLabel(priceVsBudget, config),
      weight: priceVsBudget,
    },
    {
      label: input.similarOwned ? SCORE_LABELS.similarOwnedYes : SCORE_LABELS.similarOwnedNo,
      weight: similarOwnedPoints(input.similarOwned),
    },
    {
      label: input.detectedSaleLanguage ? SCORE_LABELS.saleYes : SCORE_LABELS.saleNo,
      weight: saleUrgencyPoints(input.detectedSaleLanguage),
    },
    {
      label: recencyLabel(recency, config),
      weight: recency,
    },
    categoryRegretFactor(input.categoryRegretStats, config),
  ];

  const rawTotal = factors.reduce((sum, factor) => sum + factor.weight, 0);
  const score = Math.min(scoreCap(config), Math.round(rawTotal));

  return {
    score,
    verdict: verdictFor(score, config),
    factorBreakdown: { version: config.version, factors },
    pauseHours,
  };
}

export function parseStoredFactorBreakdown(value: unknown): StoredFactorBreakdown {
  if (!isRecord(value)) {
    return { version: SCORING_CONFIG.version, factors: [] };
  }

  const version = typeof value.version === 'number' ? value.version : SCORING_CONFIG.version;
  const factors = Array.isArray(value.factors) ? value.factors.filter(isScoreFactor) : [];
  return { version, factors };
}

function youDecide(label: string, pauseHours: number, config: ScoringConfigV1): ScoreComputation {
  return {
    // The column is a required Int; 0 is a sentinel the YOU_DECIDE verdict
    // distinguishes from a real zero-risk score.
    score: 0,
    verdict: Verdict.YOU_DECIDE,
    factorBreakdown: { version: config.version, factors: [{ label, weight: 0 }] },
    pauseHours,
  };
}

function priceVsBudgetLabel(weight: number, config: ScoringConfigV1): string {
  const { max } = config.weights.priceVsBudget;
  if (weight >= max) {
    return SCORE_LABELS.priceHigh;
  }
  if (weight >= max / 2) {
    return SCORE_LABELS.priceModerate;
  }
  return SCORE_LABELS.priceLow;
}

function recencyLabel(points: number, config: ScoringConfigV1): string {
  const [withinHour, withinDay, withinWeek] = config.recencyBuckets;
  if (points === withinHour.points) {
    return SCORE_LABELS.recencyHour;
  }
  if (points === withinDay.points) {
    return SCORE_LABELS.recencyDay;
  }
  if (points === withinWeek.points) {
    return SCORE_LABELS.recencyWeek;
  }
  return SCORE_LABELS.recencyOlder;
}

function categoryRegretFactor(
  stats: CategoryRegretStatsInput | null,
  config: ScoringConfigV1,
): ScoreFactor {
  const weight = categoryRegretRatePoints(stats, config);
  const { max, minSampleSize } = config.weights.categoryRegretRate;
  const insufficient = stats === null || stats.sampleSize < minSampleSize;

  if (insufficient) {
    return { label: SCORE_LABELS.categoryInsufficient, weight };
  }
  if (weight >= max / 2) {
    return { label: SCORE_LABELS.categoryHigh, weight };
  }
  if (weight > 0) {
    return { label: SCORE_LABELS.categoryModerate, weight };
  }
  return { label: SCORE_LABELS.categoryLow, weight };
}

function lastOf<T>(items: readonly T[]): T {
  const last = items[items.length - 1];
  if (last === undefined) {
    throw new Error('SCORING_CONFIG is missing a catch-all band');
  }
  return last;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isScoreFactor(value: unknown): value is ScoreFactor {
  return isRecord(value) && typeof value.label === 'string' && typeof value.weight === 'number';
}
